version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:

    commands:

      - echo Build started on `date`
      - echo Building the Docker image... 

      - cd docker

      - cd php-fpm
      - docker build -t $IMAGE_REPO_NAME:php-fpm-$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:php-fpm-$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:php-fpm-$IMAGE_TAG

      - cd ../nginx 
      - docker build -t $IMAGE_REPO_NAME:nginx-$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:nginx-$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:nginx-$IMAGE_TAG

  post_build:

    commands:

      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:php-fpm-$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:nginx-$IMAGE_TAG


